/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import javax.swing.JFrame;
import scooter.Scooter;
import scooter.ScooterEvento;

/**
 *
 * @author Adrián
 */
public class Control extends javax.swing.JFrame {

    private Scooter scooter;
    
    /**
     * Creates new form Control
     */
    public Control(Scooter scooter) {
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        this.scooter = scooter;
    }
    
    public void mostrar () {
        scooter.getControlador().asignarEvento(new ScooterEvento (){
            @Override
            public void onEventExecute(ScooterEvento.Evento evento) {
                switch (evento) {
                    case DESBLOQUEAR:
                        textoConectado.setText("DESBLOQUEADO");
                        botonIzquierda.setEnabled(true);
                        botonDerecha.setEnabled(true);
                        botonAbajo.setEnabled(true);
                        botonArriba.setEnabled(true);
                        break;
                    case BLOQUEAR:
                        textoConectado.setText("BLOQUEADO");
                        botonIzquierda.setEnabled(false);
                        botonDerecha.setEnabled(false);
                        botonAbajo.setEnabled(false);
                        botonArriba.setEnabled(false);
                        break;
                }
            }
        });
        
        actualizarPosicion();
        this.setVisible(true);
    }
    
    private void actualizarPosicion () {
        textoLatitud.setText(scooter.getLatitud()+"");
        textoLongitud.setText(scooter.getLongitud()+"");
    }
    
    private void mover (boolean horizontalmente, boolean aumentar) {
        float mult = aumentar ? 1 : -1;
        if (horizontalmente) {
            scooter.setLongitud(scooter.getLongitud()+ getVelocidad() * mult * 0.000001f);
        } else {
            scooter.setLatitud(scooter.getLatitud()+ getVelocidad() * mult * 0.000001f);
        }
        actualizarPosicion();
    }
    
    private float getVelocidad () {
        return sliderVelocidad.getValue();
    }
    
    public static void main(String[] args) {
        (new Control(null)).setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textoConectado = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textoLatitud = new javax.swing.JLabel();
        textoVelocidad = new javax.swing.JLabel();
        sliderVelocidad = new javax.swing.JSlider();
        jLabel7 = new javax.swing.JLabel();
        textoLongitud = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        botonAbajo = new javax.swing.JButton();
        botonIzquierda = new javax.swing.JButton();
        botonDerecha = new javax.swing.JButton();
        botonArriba = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Estado de la scooter");

        textoConectado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        textoConectado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoConectado.setText("Desconocido");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Latitude:");
        jLabel3.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Longitude:");
        jLabel4.setToolTipText("");

        textoLatitud.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        textoLatitud.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        textoLatitud.setText("1.0000");
        textoLatitud.setToolTipText("");

        textoVelocidad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        textoVelocidad.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        textoVelocidad.setText("0 km/h");
        textoVelocidad.setToolTipText("");

        sliderVelocidad.setValue(0);
        sliderVelocidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderVelocidadStateChanged(evt);
            }
        });
        sliderVelocidad.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                sliderVelocidadPropertyChange(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Velocidad:");
        jLabel7.setToolTipText("");

        textoLongitud.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        textoLongitud.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        textoLongitud.setText("1.0000");
        textoLongitud.setToolTipText("");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonAbajo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        botonAbajo.setText("v");
        botonAbajo.setMargin(new java.awt.Insets(0, 0, 0, 0));
        botonAbajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAbajoActionPerformed(evt);
            }
        });
        jPanel1.add(botonAbajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 50, 50));

        botonIzquierda.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        botonIzquierda.setText("<");
        botonIzquierda.setMargin(new java.awt.Insets(0, 0, 0, 0));
        botonIzquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIzquierdaActionPerformed(evt);
            }
        });
        jPanel1.add(botonIzquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 50, 50));

        botonDerecha.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        botonDerecha.setText(">");
        botonDerecha.setMargin(new java.awt.Insets(0, 0, 0, 0));
        botonDerecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDerechaActionPerformed(evt);
            }
        });
        jPanel1.add(botonDerecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 50, 50));

        botonArriba.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        botonArriba.setText("^");
        botonArriba.setMargin(new java.awt.Insets(0, 0, 0, 0));
        botonArriba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonArribaActionPerformed(evt);
            }
        });
        jPanel1.add(botonArriba, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 50, 50));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Controles:");
        jLabel8.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textoLatitud, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(sliderVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textoLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textoVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textoConectado, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoConectado))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(textoLatitud))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(textoLongitud))
                        .addGap(56, 56, 56)
                        .addComponent(sliderVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(textoVelocidad))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sliderVelocidadPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_sliderVelocidadPropertyChange
       
    }//GEN-LAST:event_sliderVelocidadPropertyChange

    private void sliderVelocidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderVelocidadStateChanged
        int velocidad = sliderVelocidad.getValue();
        textoVelocidad.setText(velocidad + "km/h");
    }//GEN-LAST:event_sliderVelocidadStateChanged

    private void botonArribaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonArribaActionPerformed
        mover(false, true);
    }//GEN-LAST:event_botonArribaActionPerformed

    private void botonDerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDerechaActionPerformed
        mover(true, true);
    }//GEN-LAST:event_botonDerechaActionPerformed

    private void botonAbajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAbajoActionPerformed
        mover(false, false);
    }//GEN-LAST:event_botonAbajoActionPerformed

    private void botonIzquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIzquierdaActionPerformed
        mover(true, false);
    }//GEN-LAST:event_botonIzquierdaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAbajo;
    private javax.swing.JButton botonArriba;
    private javax.swing.JButton botonDerecha;
    private javax.swing.JButton botonIzquierda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSlider sliderVelocidad;
    private javax.swing.JLabel textoConectado;
    private javax.swing.JLabel textoLatitud;
    private javax.swing.JLabel textoLongitud;
    private javax.swing.JLabel textoVelocidad;
    // End of variables declaration//GEN-END:variables
}
